### PR TITLE
update to ImageSharp 3.0

### PR DESCRIPTION
**Pull request by SimonCropp**

### CODE REVIEW

**Comment by SimonCropp** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by nima-ap** [comment]
Heads up on licensing changes that have occurred in ImageSharp v3.0.0 :)

**Comment by stesee** [comment]
> Heads up on licensing changes that have occurred in ImageSharp v3.0.0 :)

Do you see any conflict caused by their change? I am no lawyer but as long as this project stays open source think we are free to proceed.

**Comment by nima-ap** [comment]
My current understanding is that they are moving to make their product no longer free for commercial use (which makes sense).
The decision to go from v2.1.3 to v3.0.0 is likely inspired by the idea to allow existing commercial consumers on v2.1.3 to continue using the product should they wish to do so without upgrading, and also preserving all 2.x.y versions for any necessary back-port security fixes and the likes, should they wish to back-port them for free (i.e., 2.1.4, 2.1.5, etc.).

I would suggest that you do the same in that you bump major version. If in the future they do release patches for 2.1.x under the previous Apache 2-0 license, preserving your v2.x will allow you to patch your library as well to take the new dependency without forcing your consumers to bump to v3.0.0 of ImageSharp.

**Comment by stesee** [comment]
That's the plan.

**Review by stesee — APPROVED** [review]

**Pull request merged**
